apiVersion: apps/v1
kind: Deployment
metadata:
  name: masonjar-ux-deployment
spec:
  selector:
    matchLabels:
      app: masonjar-ux-latest
  template:
    metadata:
      labels:
        app: masonjar-ux-latest
    spec:
      containers:
        - name: masonjar-ux-container
          image: gcr.io/masonjar-ux-232719/masonjar-ux:latest
          imagePullPolicy: Always
          ports:
            - name: http-server
              containerPort: 80
